version: '3'

services:

  python_etl:
    image: "python:3.10-slim"
    command: bash -c "pip install /data/app/etltools/dist/etltools-0.1.0-py3-none-any.whl && python /data/app/etltools/etltools/etltools.py"
    volumes:
      - ${PWD}:/data
    depends_on:
      - postgres
    links:
      - postgres
    networks:
      - etl_network

  postgres:
    image: postgres:13.1
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "root" ]
      timeout: 45s
      interval: 10s
      retries: 5
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - APP_DB_USER=docker
      - APP_DB_PASS=docker
      - APP_DB_NAME=docker
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
    ports:
      - 5432:5432
    networks:
      - etl_network

networks:
  etl_network: null

#docker-compose -f ./pg_docker_compose_v2.yaml up -d